### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by ssouza** [slater1/tcxmill#5]
* Example: **res/10km-2019-10-18**

**Error**

```shell
$ python3 tcxmill.py activity.tcx 11.5 -u km/h
usage: tcxmill.py [-h] [-s SPEEDS [SPEEDS ...]] [-d DISTANCES [DISTANCES ...]] [-o [OUTPUT]] [-u [UNITS]] [-v [VERBOSITY]] [-a [ADD]] input
tcxmill.py: error: unrecognized arguments: 11.5
```

**Comment by slater1** [comment]
Hey there, I think you're close but missing `-s`. Can you try 

```python3 tcxmill.py activity.tcx -s 11.5 -u km/h```

**Comment by slater1** [comment]
I see now that the examples are broken. Sorry about that, I will fix them.

**Comment by ssouza** [comment]
Thank you.
But can I clear all laps in an activity, and generate new laps based on distance?

**Comment by slater1** [comment]
Thanks to [the contribution from](https://github.com/slater1/tcxmill/pull/4) @massacration , you can with the ```--distances``` option. Please look at Example 4 in README.md.
