### ISSUE TITLE
unicode problem

### ISSUE THREAD

**Issue by andrej191** [slater1/tcxmill#6]
Hi, I tried to use tcxmill but on my case it failed to create an output file because of an unsupported char. I had to change the line 401 to "_**with open(file, "w", encoding="utf-8") as f2:**_"  and then it worked.  Otherwise, nice tool. It helped me. Thank you.

**Comment by slater1** [comment]
Thanks for the bug. I've fixed it in [commit 9cf696fdcbc6b9d6e8d746df6a8286334cb09c59](https://github.com/slater1/tcxmill/commit/9cf696fdcbc6b9d6e8d746df6a8286334cb09c59)

I'm glad tcxmill helped you! I use it after almost every treadmill run.
